// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataCollectionIrrigated.proto

package grpc.unary Smart Farming;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartFarming.Empty)
    com.google.protobuf.MessageOrBuilder {
}
