// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataCollectionIrrigated.proto

package grpc.unary Smart Farming;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartFarming.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SmartFarming.Message.Enum detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.SmartFarming.Message.Enum detail = 1;</code>
   */
  grpc.unary Smart Farming.Message.Enum getDetail();
}
