// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataCollectionCheck.proto

package grpc.unary Smart Farming;

public interface RequestPhotoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartFarming.RequestPhoto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string photo = 1;</code>
   */
  java.lang.String getPhoto();
  /**
   * <code>string photo = 1;</code>
   */
  com.google.protobuf.ByteString
      getPhotoBytes();
}
