// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataCollectionIrrigated.proto

package grpc.unary Smart Farming;

public final class Smart Farming {
  private Smart Farming() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartFarming_RequestStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartFarming_RequestStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartFarming_StatusIrrigation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartFarming_StatusIrrigation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartFarming_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartFarming_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartFarming_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartFarming_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035DataCollectionIrrigated.proto\022\014SmartFa" +
      "rming\"\037\n\rRequestStatus\022\016\n\006status\030\001 \001(\t\"\"" +
      "\n\020StatusIrrigation\022\016\n\006status\030\001 \001(\t\"s\n\007Me" +
      "ssage\022*\n\006detail\030\001 \001(\0162\032.SmartFarming.Mes" +
      "sage.Enum\"<\n\004Enum\022\021\n\rNot_Irrigated\020\000\022\r\n\t" +
      "Irrigated\020\001\022\022\n\016Wait_Irrigated\020\002\"\007\n\005Empty" +
      "2\241\001\n\027DataCollectionIrrigated\022O\n\016Irrigate" +
      "dareas\022\033.SmartFarming.RequestStatus\032\036.Sm" +
      "artFarming.StatusIrrigation\"\000\0225\n\005empty\022\025" +
      ".SmartFarming.Message\032\023.SmartFarming.Emp" +
      "ty\"\000B+\n\030grpc.unary Smart FarmingB\rSmart " +
      "FarmingP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartFarming_RequestStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartFarming_RequestStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartFarming_RequestStatus_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_SmartFarming_StatusIrrigation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartFarming_StatusIrrigation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartFarming_StatusIrrigation_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_SmartFarming_Message_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartFarming_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartFarming_Message_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_SmartFarming_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartFarming_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartFarming_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
