// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductQualityType.proto

package grpc.clientStream Smart Farming;

public interface BetterGrainOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartFarming.BetterGrain)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
