// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImprovingDistributor.proto

package grpc.clientStream Smart Farming;

public interface DistribuitorAvailableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartFarming.DistribuitorAvailable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
