// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImprovingDistributor.proto

package grpc.clientStream Smart Farming;

public interface RequestDistribuitorsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartFarming.RequestDistribuitors)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string status = 3;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
