// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductQualityType.proto

package grpc.clientStream Smart Farming;

public final class Smart Farming {
  private Smart Farming() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartFarming_BetterGrain_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartFarming_BetterGrain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartFarming_RequestGrainType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartFarming_RequestGrainType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ProductQualityType.proto\022\014SmartFarming" +
      "\"\033\n\013BetterGrain\022\014\n\004type\030\001 \001(\t\" \n\020Request" +
      "GrainType\022\014\n\004type\030\001 \001(\t2U\n\tGrainType\022H\n\t" +
      "TypeGrain\022\036.SmartFarming.RequestGrainTyp" +
      "e\032\031.SmartFarming.BetterGrain(\001B2\n\037grpc.c" +
      "lientStream Smart FarmingB\rSmart Farming" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartFarming_BetterGrain_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartFarming_BetterGrain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartFarming_BetterGrain_descriptor,
        new java.lang.String[] { "Type", });
    internal_static_SmartFarming_RequestGrainType_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartFarming_RequestGrainType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartFarming_RequestGrainType_descriptor,
        new java.lang.String[] { "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
