// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImprovingDate.proto

package grpc.examples.serverstreamstrings;

public interface HarvestDateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.HarvestDate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string val = 1;</code>
   */
  java.lang.String getVal();
  /**
   * <code>string val = 1;</code>
   */
  com.google.protobuf.ByteString
      getValBytes();
}
