// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImprovingDate.proto

package grpc.examples.serverstreamstrings;

public interface InformationMonthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strings.InformationMonth)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bestmonth = 1;</code>
   */
  java.lang.String getBestmonth();
  /**
   * <code>string bestmonth = 1;</code>
   */
  com.google.protobuf.ByteString
      getBestmonthBytes();

  /**
   * <code>string worstmonth = 2;</code>
   */
  java.lang.String getWorstmonth();
  /**
   * <code>string worstmonth = 2;</code>
   */
  com.google.protobuf.ByteString
      getWorstmonthBytes();

  /**
   * <code>int32 day = 3;</code>
   */
  int getDay();
}
