// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImprovingDate.proto

package grpc.examples.serverstreamstrings;

/**
 * Protobuf type {@code strings.InformationMonth}
 */
public  final class InformationMonth extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:strings.InformationMonth)
    InformationMonthOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InformationMonth.newBuilder() to construct.
  private InformationMonth(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InformationMonth() {
    bestmonth_ = "";
    worstmonth_ = "";
    day_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InformationMonth(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            bestmonth_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            worstmonth_ = s;
            break;
          }
          case 24: {

            day_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.examples.serverstreamstrings.StringsServiceImpl.internal_static_strings_InformationMonth_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.examples.serverstreamstrings.StringsServiceImpl.internal_static_strings_InformationMonth_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.examples.serverstreamstrings.InformationMonth.class, grpc.examples.serverstreamstrings.InformationMonth.Builder.class);
  }

  public static final int BESTMONTH_FIELD_NUMBER = 1;
  private volatile java.lang.Object bestmonth_;
  /**
   * <code>string bestmonth = 1;</code>
   */
  public java.lang.String getBestmonth() {
    java.lang.Object ref = bestmonth_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bestmonth_ = s;
      return s;
    }
  }
  /**
   * <code>string bestmonth = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBestmonthBytes() {
    java.lang.Object ref = bestmonth_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bestmonth_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WORSTMONTH_FIELD_NUMBER = 2;
  private volatile java.lang.Object worstmonth_;
  /**
   * <code>string worstmonth = 2;</code>
   */
  public java.lang.String getWorstmonth() {
    java.lang.Object ref = worstmonth_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      worstmonth_ = s;
      return s;
    }
  }
  /**
   * <code>string worstmonth = 2;</code>
   */
  public com.google.protobuf.ByteString
      getWorstmonthBytes() {
    java.lang.Object ref = worstmonth_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      worstmonth_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DAY_FIELD_NUMBER = 3;
  private int day_;
  /**
   * <code>int32 day = 3;</code>
   */
  public int getDay() {
    return day_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBestmonthBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bestmonth_);
    }
    if (!getWorstmonthBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, worstmonth_);
    }
    if (day_ != 0) {
      output.writeInt32(3, day_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBestmonthBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bestmonth_);
    }
    if (!getWorstmonthBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, worstmonth_);
    }
    if (day_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, day_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.examples.serverstreamstrings.InformationMonth)) {
      return super.equals(obj);
    }
    grpc.examples.serverstreamstrings.InformationMonth other = (grpc.examples.serverstreamstrings.InformationMonth) obj;

    boolean result = true;
    result = result && getBestmonth()
        .equals(other.getBestmonth());
    result = result && getWorstmonth()
        .equals(other.getWorstmonth());
    result = result && (getDay()
        == other.getDay());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BESTMONTH_FIELD_NUMBER;
    hash = (53 * hash) + getBestmonth().hashCode();
    hash = (37 * hash) + WORSTMONTH_FIELD_NUMBER;
    hash = (53 * hash) + getWorstmonth().hashCode();
    hash = (37 * hash) + DAY_FIELD_NUMBER;
    hash = (53 * hash) + getDay();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.examples.serverstreamstrings.InformationMonth parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.examples.serverstreamstrings.InformationMonth parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.examples.serverstreamstrings.InformationMonth parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.examples.serverstreamstrings.InformationMonth parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.examples.serverstreamstrings.InformationMonth parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.examples.serverstreamstrings.InformationMonth parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.examples.serverstreamstrings.InformationMonth parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.examples.serverstreamstrings.InformationMonth parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.examples.serverstreamstrings.InformationMonth parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.examples.serverstreamstrings.InformationMonth parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.examples.serverstreamstrings.InformationMonth parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.examples.serverstreamstrings.InformationMonth parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.examples.serverstreamstrings.InformationMonth prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code strings.InformationMonth}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:strings.InformationMonth)
      grpc.examples.serverstreamstrings.InformationMonthOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.examples.serverstreamstrings.StringsServiceImpl.internal_static_strings_InformationMonth_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.examples.serverstreamstrings.StringsServiceImpl.internal_static_strings_InformationMonth_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.examples.serverstreamstrings.InformationMonth.class, grpc.examples.serverstreamstrings.InformationMonth.Builder.class);
    }

    // Construct using grpc.examples.serverstreamstrings.InformationMonth.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bestmonth_ = "";

      worstmonth_ = "";

      day_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.examples.serverstreamstrings.StringsServiceImpl.internal_static_strings_InformationMonth_descriptor;
    }

    @java.lang.Override
    public grpc.examples.serverstreamstrings.InformationMonth getDefaultInstanceForType() {
      return grpc.examples.serverstreamstrings.InformationMonth.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.examples.serverstreamstrings.InformationMonth build() {
      grpc.examples.serverstreamstrings.InformationMonth result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.examples.serverstreamstrings.InformationMonth buildPartial() {
      grpc.examples.serverstreamstrings.InformationMonth result = new grpc.examples.serverstreamstrings.InformationMonth(this);
      result.bestmonth_ = bestmonth_;
      result.worstmonth_ = worstmonth_;
      result.day_ = day_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.examples.serverstreamstrings.InformationMonth) {
        return mergeFrom((grpc.examples.serverstreamstrings.InformationMonth)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.examples.serverstreamstrings.InformationMonth other) {
      if (other == grpc.examples.serverstreamstrings.InformationMonth.getDefaultInstance()) return this;
      if (!other.getBestmonth().isEmpty()) {
        bestmonth_ = other.bestmonth_;
        onChanged();
      }
      if (!other.getWorstmonth().isEmpty()) {
        worstmonth_ = other.worstmonth_;
        onChanged();
      }
      if (other.getDay() != 0) {
        setDay(other.getDay());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.examples.serverstreamstrings.InformationMonth parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.examples.serverstreamstrings.InformationMonth) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object bestmonth_ = "";
    /**
     * <code>string bestmonth = 1;</code>
     */
    public java.lang.String getBestmonth() {
      java.lang.Object ref = bestmonth_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bestmonth_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bestmonth = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBestmonthBytes() {
      java.lang.Object ref = bestmonth_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bestmonth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bestmonth = 1;</code>
     */
    public Builder setBestmonth(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bestmonth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bestmonth = 1;</code>
     */
    public Builder clearBestmonth() {
      
      bestmonth_ = getDefaultInstance().getBestmonth();
      onChanged();
      return this;
    }
    /**
     * <code>string bestmonth = 1;</code>
     */
    public Builder setBestmonthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bestmonth_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object worstmonth_ = "";
    /**
     * <code>string worstmonth = 2;</code>
     */
    public java.lang.String getWorstmonth() {
      java.lang.Object ref = worstmonth_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        worstmonth_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string worstmonth = 2;</code>
     */
    public com.google.protobuf.ByteString
        getWorstmonthBytes() {
      java.lang.Object ref = worstmonth_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        worstmonth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string worstmonth = 2;</code>
     */
    public Builder setWorstmonth(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      worstmonth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string worstmonth = 2;</code>
     */
    public Builder clearWorstmonth() {
      
      worstmonth_ = getDefaultInstance().getWorstmonth();
      onChanged();
      return this;
    }
    /**
     * <code>string worstmonth = 2;</code>
     */
    public Builder setWorstmonthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      worstmonth_ = value;
      onChanged();
      return this;
    }

    private int day_ ;
    /**
     * <code>int32 day = 3;</code>
     */
    public int getDay() {
      return day_;
    }
    /**
     * <code>int32 day = 3;</code>
     */
    public Builder setDay(int value) {
      
      day_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 day = 3;</code>
     */
    public Builder clearDay() {
      
      day_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:strings.InformationMonth)
  }

  // @@protoc_insertion_point(class_scope:strings.InformationMonth)
  private static final grpc.examples.serverstreamstrings.InformationMonth DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.examples.serverstreamstrings.InformationMonth();
  }

  public static grpc.examples.serverstreamstrings.InformationMonth getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InformationMonth>
      PARSER = new com.google.protobuf.AbstractParser<InformationMonth>() {
    @java.lang.Override
    public InformationMonth parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InformationMonth(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InformationMonth> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InformationMonth> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.examples.serverstreamstrings.InformationMonth getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

