// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImprovingDate.proto

package grpc.examples.serverstreamstrings;

public final class StringsServiceImpl {
  private StringsServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strings_HarvestDate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strings_HarvestDate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strings_InformationMonth_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strings_InformationMonth_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ImprovingDate.proto\022\007strings\"\032\n\013Harves" +
      "tDate\022\013\n\003val\030\001 \001(\t\"F\n\020InformationMonth\022\021" +
      "\n\tbestmonth\030\001 \001(\t\022\022\n\nworstmonth\030\002 \001(\t\022\013\n" +
      "\003day\030\003 \001(\0052R\n\016StringsService\022@\n\013harvestD" +
      "ate\022\024.strings.HarvestDate\032\031.strings.Info" +
      "rmationMonth0\001B9\n!grpc.examples.serverst" +
      "reamstringsB\022StringsServiceImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_strings_HarvestDate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_strings_HarvestDate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strings_HarvestDate_descriptor,
        new java.lang.String[] { "Val", });
    internal_static_strings_InformationMonth_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_strings_InformationMonth_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strings_InformationMonth_descriptor,
        new java.lang.String[] { "Bestmonth", "Worstmonth", "Day", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
