// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductQualityData.proto

package grpc.bidirectional Smart Farming;

public interface BestGrainsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartFarming.BestGrains)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string type = 2;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>int32 date = 3;</code>
   */
  int getDate();
}
