// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductQualityData.proto

package grpc.bidirectional Smart Farming;

public final class Smart Farming {
  private Smart Farming() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartFarming_Request_Harvest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartFarming_Request_Harvest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartFarming_BestGrains_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartFarming_BestGrains_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ProductQualityData.proto\022\014SmartFarming" +
      "\";\n\017Request_Harvest\022\014\n\004name\030\001 \001(\t\022\014\n\004typ" +
      "e\030\002 \001(\t\022\014\n\004date\030\003 \001(\005\"6\n\nBestGrains\022\014\n\004n" +
      "ame\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\014\n\004date\030\003 \001(\0052a\n" +
      "\022ProductQualityData\022K\n\ndataHavest\022\035.Smar" +
      "tFarming.Request_Harvest\032\030.SmartFarming." +
      "BestGrains\"\000(\0010\001B3\n grpc.bidirectional S" +
      "mart FarmingB\rSmart FarmingP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SmartFarming_Request_Harvest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartFarming_Request_Harvest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartFarming_Request_Harvest_descriptor,
        new java.lang.String[] { "Name", "Type", "Date", });
    internal_static_SmartFarming_BestGrains_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartFarming_BestGrains_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartFarming_BestGrains_descriptor,
        new java.lang.String[] { "Name", "Type", "Date", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
