// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataCollectionIrrigated.proto

package grpc.unaryfarmingsmart;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FarmingSmart.Empty)
    com.google.protobuf.MessageOrBuilder {
}
