// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataCollectionIrrigated.proto

package grpc.unaryfarmingsmart;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FarmingSmart.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.FarmingSmart.Message.Enum detail = 1;</code>
   */
  int getDetailValue();
  /**
   * <code>.FarmingSmart.Message.Enum detail = 1;</code>
   */
  grpc.unaryfarmingsmart.Message.Enum getDetail();
}
