// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataCollectionIrrigated.proto

package grpc.unaryfarmingsmart;

public final class StringsServiceImplementation {
  private StringsServiceImplementation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FarmingSmart_StringRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FarmingSmart_StringRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FarmingSmart_StringResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FarmingSmart_StringResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FarmingSmart_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FarmingSmart_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FarmingSmart_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FarmingSmart_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035DataCollectionIrrigated.proto\022\014Farming" +
      "Smart\"\036\n\rStringRequest\022\r\n\005photo\030\001 \001(\t\"\037\n" +
      "\016StringResponse\022\r\n\005photo\030\001 \001(\t\"`\n\007Messag" +
      "e\022*\n\006detail\030\001 \001(\0162\032.FarmingSmart.Message" +
      ".Enum\")\n\004Enum\022\010\n\004GOOD\020\000\022\016\n\nACCEPTABLE\020\001\022" +
      "\007\n\003BAD\020\002\"\007\n\005Empty2\224\001\n\016DataCollection\022K\n\014" +
      "checkPlantio\022\033.FarmingSmart.StringReques" +
      "t\032\034.FarmingSmart.StringResponse\"\000\0225\n\005emp" +
      "ty\022\025.FarmingSmart.Message\032\023.FarmingSmart" +
      ".Empty\"\000B8\n\026grpc.unaryfarmingsmartB\034Stri" +
      "ngsServiceImplementationP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_FarmingSmart_StringRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FarmingSmart_StringRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FarmingSmart_StringRequest_descriptor,
        new java.lang.String[] { "Photo", });
    internal_static_FarmingSmart_StringResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FarmingSmart_StringResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FarmingSmart_StringResponse_descriptor,
        new java.lang.String[] { "Photo", });
    internal_static_FarmingSmart_Message_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FarmingSmart_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FarmingSmart_Message_descriptor,
        new java.lang.String[] { "Detail", });
    internal_static_FarmingSmart_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_FarmingSmart_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FarmingSmart_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
