// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataCollectionIrrigated.proto

package grpc.unaryfarmingsmart;

public interface StringRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FarmingSmart.StringRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string photo = 1;</code>
   */
  java.lang.String getPhoto();
  /**
   * <code>string photo = 1;</code>
   */
  com.google.protobuf.ByteString
      getPhotoBytes();
}
